on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Get Pokemon name
        uses: ./ # Uses an action in the root directory
        id: pokemon
        with:
          filename: .env
